### ISSUE TITLE
Parser: Comparison expression with assignment

### ISSUE THREAD

**Issue by joehoyle** [pxp-lang/pxp#73]
I noticed that given the code `true !== $a = true` gets parsed to a StoreVariable expression with `(true !== $a) (true)` rather than `true !== ( $a = true )` which seems odd, as the expression evaluation order is the latter

**Comment by ryangjchandler** [comment]
This sounds like a precedence issue, investigating!

**Comment by ryangjchandler** [comment]
So I've done some digging, it seems this is a bit of a problem with using a strict precedence system for parsing expressions. I did some source diving inside of `microsoft/tolerant-php-parser` and they seem to have some special logic to handle this specific scenario because their precedence system is essentially identical to mine.

I'm going to think about the best way to handle this, since the AST representations are very different (we have separate expression nodes for different types of operation, they just have a single "binary expression" node).

**Comment by ryangjchandler** [comment]
@joehoyle I've had a crack at fixing this so give it a go and let me know. I really need to go through and right some proper tests for the precedence system, but I've added in a test case for this to avoid future regressions.
